"""Optional Korean romanization provider powered by Koroman."""
from __future__ import annotations

import re


_HANGUL_RUN = re.compile(r"[\uac00-\ud7a3]+")


class KoreanRomanizationPlugin:
    name = "Korean Romanization"
    version = "1.0.0"
    description = (
        "Generate pronunciation-aware Revised Romanization using Koroman."
    )

    def on_load(self, context):
        try:
            from koroman import romanize
        except Exception as error:
            context.api.log(f"Koroman unavailable: {error}")
            return

        def build(text):
            """Return ruby-compatible segments.

            Korean runs are kept together so ruby stays word-like instead of
            placing one romanized syllable above every Hangul syllable.
            Koroman handles phonological changes inside each contiguous Hangul
            run; spaces, punctuation, Latin text, etc. remain untouched.
            """
            text = str(text or "")
            if not text:
                return []

            result = []
            position = 0

            for match in _HANGUL_RUN.finditer(text):
                if match.start() > position:
                    result.append({
                        "text": text[position:match.start()],
                        "reading": None,
                    })

                surface = match.group(0)
                try:
                    # Koroman's use_hyphen option is opt-in.  The previous
                    # implementation called romanize(surface) first, which
                    # succeeds and therefore never reached the option branch.
                    reading = str(
                        romanize(surface, use_hyphen=True)
                    ).strip()
                except Exception as error:
                    context.api.log(
                        f"Koroman failed for {surface!r}: {error!r}"
                    )
                    reading = ""

                result.append({
                    "text": surface,
                    "reading": reading or None,
                })
                position = match.end()

            if position < len(text):
                result.append({"text": text[position:], "reading": None})

            return result

        def can_handle(text, *, language=None):
            # The provider owns Hangul detection; callers do not need to know
            # that Korean exists. Mixed-script lines are supported too.
            return any("\uac00" <= char <= "\ud7a3" for char in str(text or ""))

        context.api.register_reading_provider(
            "korean",
            "Korean Romanization",
            build,
            description=(
                "Pronunciation-aware Revised Romanization generated by Koroman."
            ),
            can_handle=can_handle,
        )
        context.api.log(
            "Korean Romanization provider registered through Plugin API v2"
        )


PLUGIN_CLASS = KoreanRomanizationPlugin
